#' Fit the envelope based sparse partial least squares model.
#'
#' @details This function fits the sparse envelope model to the predictor using the maximum likelihood estimation. When the dimension of the envelope is between 1 and p-1, we implemented the algorithm in G. Zhu and Z. Su (2017). When the dimension is p, then the envelope model degenerates to the standard multivariate linear regression. When the dimension is 0, it means that X and Y are uncorrelated, and the fitting is different.
#'
#'
#' @param X Predictors. An n by p matrix, p is the number of predictors. The predictors can be univariate or multivariate, discrete or continuous.
#'
#' @param Y Multivariate responses. An n by r matrix, r is the number of responses and n is the number of observations. The responses must be continuous variables.
#'
#' @param u Dimension of the envelope. An integer between 0 and p.
#'
#' @param lambda1 A user supplied lambda sequence for the first stage.
#'
#' @param lambda2 A user supplied lambda sequence for the second stage.
#'
#' @param maxiter Maximum number of iterations. Default value: 100.
#'
#' @param ftol Tolerance parameter for F. Default value: 1e-4.
#'
#' @param init The initial value for the envelope subspace. An p by u matrix. Default value is the one generated by function initial_value.
#'
#' @param asym Flag for calculating the asymptotic covariance of vec(beta) and asymptotic standard error for elements in beta for a fitted envelope model, logical 0 or 1. Default value: 0.
#'
#' @param verbose Flag for print out model fitting process, logical 0 or 1. Default value: 0.
#'
#' @return
#'
#' \item{mu}{The estimated intercept in the envelope model. An r by 1 vector.}
#' \item{beta}{The envelope estimator of the regression coefficients beta. A p by r matrix.}
#' \item{Gamma}{The orthogonal basis of the envelope subspace. A p by u semi-orthogonal matrix.}
#' \item{Gamma0}{The orthogonal basis of the complement of the envelope subspace. An p by p-u semi-orthogonal matrix.}
#' \item{eta}{The coordinates of beta with respect to Gamma. A u by r matrix.}
#' \item{SigX}{The envelope estimator of the covariance matrix of X. An p by p matrix.}
#' \item{Omega}{The coordinates of Sigma with respect to Gamma. A u by u matrix.}
#' \item{Omega0}{The coordinates of Sigma with respect to Gamma0. A p-u by p-u matrix.}
#' \item{sigYcX}{The estimated conditional covariance matrix of Y given X. An r by r matrix.}
#' \item{loglik}{The maximized log likelihood function. A real number.}
#' \item{paramNum}{The number of parameters in the envelope model. A positive integer.}
#' \item{n}{The number of observations in the data. A positive integer.}
#' \item{q}{The number of active response variables. A positive integer.}
#' \item{iternum}{The number of iterations. A positive integer.}
#' \item{lambda}{The tuning parameters chosen by BIC.}
#' \item{where_1}{The active responses chosen by the sparse envelope model.}
#' \item{where_0}{The inactive responses chosen by the sparse envelope model.}
#' \item{BIC_seq1}{The sequence of BIC in the first stage.}
#' \item{BIC_seq2}{The sequence of BIC in the second stage.}
#' \item{covMatrix}{The asymptotic covariance of vec(beta). An pr by pr matrix. The covariance matrix returned are asymptotic. For the actual standard errors, multiply by 1/n.}
#' \item{asySE}{The asymptotic standard error for elements in beta under the envelope model. An p by r matrix. The standard errors returned are asymptotic, for actual standard errors, multiply by 1/sqrt(n).}
#' \item{ratio}{The asymptotic standard error ratio of the standard multivariate linear regression estimator over the envelope estimator, for each element in beta. An r by p matrix.}
#' \item{fit_time}{The time costs for fitting the envelope model.}
#'
#' @references#'
#' The codes are implemented based on the algorithm in Guangyu Zhu. Zhihua Su. "Envelope-based sparse partial least squares." Ann. Statist. 48 (1) 161 - 182, February 2020. \href{https://doi.org/10.1214/18-AOS1796}
#'
#' @author#'
#' Guangyu Zhu and Zhihua Su
#'
#' @seealso
#'
#' \code{choose_spxenv} for choosing the dimension of envelope subspace and the tuning parameter.
#' @export
spxenv <- function(X, Y, u, lambda1=NULL,lambda2=NULL, ftol=1e-2, maxiter=1e2,eps2=1e-4,init=NULL,asy=0,verbose=0,init_method=1,lambda_spice=0.1)
{
  t1 = proc.time()
  X=as.matrix(X)
  Y=as.matrix(Y)
  p = ncol(X)
  r = ncol(Y)
  n = nrow(X)
  if(u==0||u==p) out=xenv(X,Y,u,0)
  else{
    if(missing(lambda1)) lambda1 <- exp(seq(log(1),log(1e-3),len=5))
    if(missing(lambda2)) lambda2 <- exp(seq(log(1),log(1e-3),len=5))
    if(missing(init)){
      init=init_spxenv(X,Y,u=u,lambda_spice=lambda_spice,init_method=init_method)
    }
    GEidx = GE(init)
    newX = X[, GEidx,drop=FALSE]
    newinit=init[GEidx,,drop=FALSE]

    m1 <- LassoLambda.spxenv(newX, Y, u, ftol=ftol, maxiter=maxiter, eps2=eps2, lambda=lambda1, weight = rep(1,p-u),init=newinit,verbose=verbose)    #calculating weight

    #calculating weight
    Gammahat <- m1$Gamma
    w <- Gammahat %*% solve(Gammahat[1:u, ])
    w_norm <- 1/(rowSums(w^2)^2)[(u+1):p]
    #w_norm2 <- 1/(rowSums(Gammahat^2)^2)[(u+1):p]
    if(verbose) {print(w);cat('weights:',w_norm,'\n')}
    #adaptive lasso step
    m2 <- LassoLambda.spxenv(newX, Y, u,  lambda=lambda2,ftol=ftol, maxiter=maxiter,eps2=eps2, weight =
                               w_norm,init=Gammahat,verbose=verbose)
    out=m2
    out$beta=m2$beta[order(GEidx),,drop=FALSE]
    out$Gamma=m2$Gamma[order(GEidx),,drop=FALSE]
    out$Gamma0=m2$Gamma0[order(GEidx),,drop=FALSE]
    rownames(out$beta)=colnames(X)
    rownames(out$Gamma)=colnames(X)
    out$where1=     sort(GEidx[m2$where1])
    out$where0= setdiff(1:p,sort(GEidx[m2$where1]))
    out$BIC_seq = NULL
    out$BIC_seq1=m1$BIC_seq
    out$BIC_seq2=m2$BIC_seq
    lambdas=c(m1$lambda,m2$lambda)
    names(lambdas)=c('first stage','second stage')
    out$lambda=lambdas
  }
  if(asy){
    Yc <- as.matrix(scale(Y, center = T, scale = FALSE))
    Xc <- as.matrix(scale(X, center = T, scale = FALSE))
    sigY <- stats::cov(Yc) * (n-1)/n
    sigX <- stats::cov(Xc) * (n-1)/n
    sigXY <- stats::cov(Xc, Yc) * (n-1)/n
    tmp = chol(sigX) # t(tmp)%*%tmp =sigX
    invsigX <- chol2inv(tmp) # invsigX=tmp2%*%t(tmp2)
    tmp2 <- backsolve(tmp, diag(p)) # tmp2=inv(tmp)
    tmp3 <- crossprod(sigXY, tmp2)
    sigYcX = sigY - tcrossprod(tmp3,tmp3) #sigYX %*% invsigX%*% t(sigYX)
    betaOLS <- invsigX%*%sigXY
    if(u==0){
      out$covMatrix = NULL
      out$asySE = NULL
      out$ratio = matrix(1,p, r)
    } # u==0
    else if(u==p){
      covMatrix = kronecker(sigYcX, invsigX);
      asyFm = matrix(sqrt(diag(covMatrix)), p,r)
      out$covMatrix = covMatrix
      out$asySE = asyFm
      out$ratio = matrix(1, p, r)
    } # u==p
    else{
      q = out$q
      idx=out$where1
      idx2 = rep(0,q*r)
      for (k in 1:r)    idx2[((k-1)*q+1) : (k*q)]= idx+(k-1)*p
      if(q>u){
        eta=out$eta
        Omega=out$Omega
        Gamma=out$Gamma
        invsigYcX=chol2inv(chol(sigYcX))
        invOmega=chol2inv(chol(Omega))
        Gamma_work=Gamma[idx,]
        Gamma0_work=grams(nulbasis(t(Gamma_work)))
        #---compute asymptotic variance and get the ratios---
        asyFm = kronecker(sigYcX, invsigX)
        asyFm = matrix(sqrt(diag(asyFm)), p, r)
        Omega0_1 = t(Gamma0_work) %*% sigX[idx, idx] %*% Gamma0_work
        Omega0_2 = sigX[idx_i, idx_i];  # r-q by r-q
        Omega0_12 = t(G0_work) %*% sigX[idx, idx_i]; # q-u by r-q
        Omega0_1c2 = Omega0_1 - Omega0_12 %*% solve(Omega0_2) %*% t(Omega0_12); # q-u by q-u
        invOmega0_1c2 = chol2inv(chol(Omega0_1c2))

        temp = kronecker(eta %*% invsigYcX %*% t(eta), Omega0_1)+
          kronecker(Omega, invOmega0_1c2) +
          kronecker(invOmega, Omega0_1) - 2 * kronecker(diag(u), diag(q - u))
        invtemp=chol2inv(chol(temp ))
        covMatrix_work = kronecker(sigYcX, Gamma_work %*% invOmega %*% t(Gamma_work))+
          kronecker(t(eta), Gamma0_work) %*% invtemp %*% kronecker(eta, t(Gamma0_work))
        covMatrix = matrix(0,p*r,p*r);   #pr by pr
        covMatrix[idx2,idx2] = covMatrix_work;
        asySE = matrix(sqrt(diag(covMatrix)), p, r)
        out$covMatrix = covMatrix
        out$asySE = asySE
        out$ratio = asyFm / asySE
      } #q>u
      else{
        asyFm = kronecker(sigYcX,invsigX); # rp by rp
        asyFm = matrix(sqrt(diag(asyFm)), p, r); #r by p

        sigX_work=sigX[idx,idx]
        invsigX_work=chol2inv(chol(sigX_work))
        sigXY_work=sigXY[idx,,drop=FALSE]
        sigYcX_work = sigY - t(sigXY_work) %*% invsigX_work %*% sigXY_work
        covMatrix_work = kronecker(sigYcX_work, invsigX_work) # qp by qp
        covMatrix=matrix(0,r*p,r*p)  #rp by rp
        covMatrix[idx2,idx2]=covMatrix_work;
        asySE = matrix(sqrt(diag(covMatrix)), p, r); #r by p
        out$covMatrix = covMatrix
        out$asySE = asySE
        out$ratio = asyFm / asySE
      } #q=u
    }
  } # asy==1
  out$fit_time=as.numeric((proc.time()-t1)[3])
  class(out)='spxenv'
  out
}
